CREATE TABLE equipments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    category VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL
);

CREATE TABLE rental_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_id BIGINT NOT NULL,
    user_name VARCHAR(100) NOT NULL,
    rented_at TIMESTAMP NOT NULL,
    returned_at TIMESTAMP NULL,
    CONSTRAINT fk_rental_records_equipment
        FOREIGN KEY (equipment_id) REFERENCES equipments (id)
);
